name: CICD using Docker
on:
 push:
jobs:
 CICD:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout the code 
     uses: actions/checkout@v3
   - name: Set up Java and Maven
     uses: actions/setup-java@v3
     with:
      java-version: '11'
      distribution: 'temurin'
      cache: maven  
   - name: setup Docker 
     uses: actions/setup-buildx-action@v2
   - name: build with maven 
     run: mvn -B package --file pom.xml
   - name: Login to docker hub
     uses: docker/login-action@v2
     with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
   - name: build the dockerfile and push
     uses: docker/build-push-action@v4
     with:
      context: .
      push: true 
      tags: ${{ secrets.DOCKERHUB_USERNAME }}/myimage01
